<<<<<<< HEAD
spring.datasource.url=${DB_URL:jdbc:h2:mem:task_manager;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=anushkab
spring.security.user.password={noop}anushkab123
spring.h2.console.enabled=true
=======
spring.datasource.url=jdbc:mysql://localhost:3306/task_manager
spring.datasource.username=root
spring.datasource.password=anushka
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=anushkab
spring.security.user.password=anushkab123
>>>>>>> 438f23f07e9de93a71c7682bf098a97a3f854a55
